# Enforce hardware-specific builds
hostonly="yes"

# Highly compressed modern standard
compress="zstd -15"

# Enable squashfs packaging to shrink the physical footprint
squash_initramfs="yes"

# Apply CPU microcode patches immediately
early_microcode="yes"

# Strip out early-boot networking
omit_dracutmodules+=" network "

# Ban unused NVIDIA opensource driver
omit_drivers+=" nouveau "
