#!/usr/bin/env bash

image=$(mktemp --suffix .png)
trap "/bin/rm -f $image" INT TERM EXIT

scrot $image
i3lock -c 000000
convert $image -blur 0x8 -paint 10  $image
kill $(pgrep i3lock)
i3lock -i $image
